CloudConsultingSalesforce/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Staff Requirement</label>
    <nameField>
        <label>Project Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Line_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Staff__c/Project_Staff__c.object-meta.xml
<CustomObject>
    <label>Project Staff</label>
    <nameField>
        <label>Project Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Staff__c/fields/Project_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Project_Line_Item__c</fullName>
    <label>Project Line Item</label>
    <referenceTo>Project_Line_Item__c</referenceTo>
    <relationshipLabel>Projects Staff</relationshipLabel>
    <relationshipName>Projects_Staff</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Staff__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects_Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

CloudConsultingSalesforce/force-app/main/default/classes/ProjectStaffTriggerHelper.cls
public class ProjectStaffTriggerHelper {
    public static void triggerBeforeInsert(List<Project_Staff__c> staffList){
        Map<Id, List<Project_Staff__c>> projectStaffByProject = new Map<Id, List<Project_Staff__c>>();
        
        Set<Id> usersId = new Set<Id>(); 
        for(Project_Staff__c staff : staffList){
            usersId.add(staff.User__c);
        }
        
        for(Project_Staff__c staff : staffList){
            if(!projectStaffByProject.containsKey(staff.Project_Line_Item__r.Project__c)){
                projectStaffByProject.put((Id)staff.Project_Line_Item__r.Project__c, new List<Project_Staff__c>{staff});
            }
            else{
                projectStaffByProject.get(staff.Project_Line_Item__r.Project__c).add(staff);
            }
        }
        
        for(Id key : projectStaffByProject.keySet()){
            //List<Project_Staff__c>ProjectClass.getAvailableUsers(key)
        }
        
    }
}