CloudConsultingSalesforce/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CloudConsultingSalesforce/force-app/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Staff Requirement</label>
    <nameField>
        <label>Project Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Line_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Line_Item__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Staff__c/Project_Staff__c.object-meta.xml
<CustomObject>
    <label>Project Staff</label>
    <nameField>
        <label>Project Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Staff__c/fields/Project_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Project_Line_Item__c</fullName>
    <label>Project Line Item</label>
    <referenceTo>Project_Line_Item__c</referenceTo>
    <relationshipLabel>Projects Staff</relationshipLabel>
    <relationshipName>Projects_Staff</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Staff__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects_Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

CloudConsultingSalesforce/force-app/main/default/classes/ProjectClass.cls
public class ProjectClass {
    //Devuelve el listado de requerimientos de staff para el proyecto.
    public static List<Project_Line_Item__c> getRequirementsForProject(Id projectId){
        List<Project_Line_Item__c> staffRequirementsInProject = [SELECT Id, Project__r.Start_Date__c, Project__r.End_Date__c, Role__c
                                      							 FROM Project_Line_Item__c WHERE Project__c = 'a035f000001JlQwAAK'];
       
        return staffRequirementsInProject;
    }
    
    //Devuelve una lista de usuarios asociados a los roles requeridos.
    public static List<User> getUserByRol(Id projectId){
        List<Project_Line_Item__c> staffRequirementsInProject = getRequirementsForProject(projectId);
        
 		List<String> rolesList = new List<String>();
        for(Project_Line_Item__c p: staffRequirementsInProject){
            rolesList.add(p.Role__c);
        }
          
   		List<User> usersByRoles = [select Id, FirstName, LastName, UserRole.Name from User where UserRole.Name in: rolesList];  
     	
        return usersByRoles;
    }
        
    //Agrupa los projects staff por usuarios.
    public static Map<Id, List<Project_Staff__c>> getProjectStaffByUser(Id projectId){
        List<User> usersByRoles = getUserByRol(projectId);
        
        List<Project_Staff__c> staffList = [SELECT Id, Project_Line_Item__r.Project__r.Start_Date__c,Project_Line_Item__r.Project__r.End_Date__c, User__c   
                                            FROM Project_Staff__c where User__c IN: usersByRoles and Project_Line_Item__r.Project__r.Stage__c != 'Completed'];
        
        Map<Id, List<Project_Staff__c>> userMap = new Map<Id, List<Project_Staff__c>>(); 
        for(User currentUser: usersByRoles){
            if(!userMap.containsKey(currentUser.Id)){
               userMap.put(currentUser.Id, new List<Project_Staff__c>()); 
            }
        }              
        for(Project_Staff__c staff: staffList){
            userMap.get(staff.user__c).add(staff);
        }
        
        return userMap;
    }
        
    //Lista los usuarios disponibles, Cuyos project staff no coinciden con lad fechas del proyecto actual.
    public static List<User> getAvailableUsers(Id projectId){ 
        Map<Id, List<Project_Staff__c>> userMap = getProjectStaffByUser(projectId);
        List<Project_Line_Item__c> staffRequirementsInProject = getRequirementsForProject(projectId);
        List<User> usersByRoles = getUserByRol(projectId);
        
        Date startProjectDate = staffRequirementsInProject[0].Project__r.Start_Date__c;
        Date endProjectDate = staffRequirementsInProject[0].Project__r.End_Date__c;
        
        List<User> availableUsers = new List<User>();
        for(Id staffId: userMap.keySet()){
            Boolean available = true;
            if(userMap.get(staffId).size()>0){
                for(Project_Staff__c PS: userMap.get(staffId)){
                    if(!((PS.Project_Line_Item__r.Project__r.Start_Date__c < startProjectDate || PS.Project_Line_Item__r.Project__r.Start_Date__c > endProjectDate) 
                       && (PS.Project_Line_Item__r.Project__r.End_Date__c < startProjectDate || PS.Project_Line_Item__r.Project__r.End_Date__c > endProjectDate))){
                           available = false;
                           break;                        
                       }
                }    
                if(available){
                    for(User userToAdd: usersByRoles){
                        if(userToAdd.Id == staffId){
                            availableUsers.add(userToAdd);
                        }
                    }
                  }
            } 
            else{
                for(User userToAdd: usersByRoles){
                    if(userToAdd.Id == staffId){
                        availableUsers.add(userToAdd);
                    }
                }               
            }
        }   

        return availableUsers;
    } 
    
    
    
    
    public static List<Map<Id, List<User>>> rodriCareta(Id projectId){
        List<User> availableUsers = getAvailableUsers(projectId);        
        
  
        return new List<Map<Id, List<User>>>();
    }
}