CloudConsultingSalesforce/force-app/main/default/objects/OpportunityLineItem__c/OpportunityLineItem__c.object-meta.xml
<CustomObject>
    <label>OpportunityLineItem</label>
    <nameField>
        <label>OpportunityLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpportunityLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsultingSalesforce/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Staff Requirement</label>
    <nameField>
        <label>Project Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Line_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsultingSalesforce/force-app/main/default/classes/TestFlowProject.cls
@IsTest
public class TestFlowProject {
    @testSetup static void setup(){
       ProjectFactory.createOpportunity(10);
    }
    
    @isTest static void testFlow(){
        List<Opportunity> oppList = [SELECT Id, Project_Manager__c FROM Opportunity];
        Test.startTest();
            for(Opportunity opp : oppList){
                opp.StageName = 'Closed Won';
            }
            update oppList;
        Test.stopTest();
        System.assertEquals(oppList.size(), [SELECT count() FROM Project__c]);
        
        System.assertEquals(oppList[0].Project_Manager__c, [SELECT Id, OwnerId FROM Project__c LIMIT 1].OwnerId);
        
        List<Project_Line_Item__c> listProjectItem = [SELECT Id FROM Project_Line_Item__c];
        List<OpportunityLineItem__c> listOppItem = [SELECT Id FROM OpportunityLineItem__c];
        
        System.assertEquals(listOppItem.size(), listProjectItem.size());
        
    }
}