CloudConsultingSalesforce/force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Staff Requirement</label>
    <nameField>
        <label>Project Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Staff__c/Project_Staff__c.object-meta.xml
<CustomObject>
    <label>Project Staff</label>
    <nameField>
        <label>Project Staff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Staff__c/fields/Project_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Project_Line_Item__c</fullName>
    <label>Project Line Item</label>
    <referenceTo>Project_Line_Item__c</referenceTo>
    <relationshipLabel>Projects Staff</relationshipLabel>
    <relationshipName>Projects_Staff</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsultingSalesforce/force-app/main/default/objects/Project_Staff__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects_Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

CloudConsultingSalesforce/force-app/main/default/classes/ProjectStaffTriggerTest.cls
@isTest
public class ProjectStaffTriggerTest {
	@testSetup
    static void setup(){
        ProjectFactory.createOpportunity(2);
        ProjectFactory.projectStaffCreator();
    }
    
    @isTest
    static void x(){
        
        Project_Staff__c ps = [SELECT Id, User__c, Start_Date__c, End_Date__c, Project_Line_Item__c FROM Project_Staff__c LIMIT 1];
        Project_Staff__c newPS = new Project_Staff__c(Name = 'Test trigger',
                                                      User__c = ps.User__c,
                                                      Project_Line_Item__c = ps.Project_Line_Item__c,
                                                      Start_Date__c = ps.Start_Date__c,
                                                      End_Date__c = ps.End_Date__c);
        try{
        	insert newPS;    
        }catch(DmlException e){
            System.assert(e.getMessage().contains('User not available'));
        }
    }
    
}